server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id:  currency-exchange
          uri: lb://currency-exchange
          predicates:
            - Path=/currency-exchange/**
        - id: currency-conversion
          uri: lb://currency-conversion
          predicates:
            - Path=/currency-conversion/**
        - id: currency-conversion
          uri: lb://currency-conversion
          predicates:
            - Path=/currency-conversion-feign/**
     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/